### ISSUE TITLE
TypeError: argument of type 'int' is not iterable in function check_response_errors

### ISSUE THREAD

**Issue by persebek** [aboul3la/Sublist3r#114]
Received the following exception:

File "/home/user/Sublist3r/sublist3r.py", line 298, in check_response_errors
if 'Our systems have detected unusual traffic' in resp:
TypeError: argument of type 'int' is not iterable

There needs to be a check for the type of the 'resp' (make sure it is a string type) variable before performing the check - if 'Our systems have detected unusual traffic' in resp:

**Comment by persebek** [comment]
Pull request #115 created to fix this issue.

**Comment by aboul3la** [comment]
Thanks for reporting this issue. It should be fixed now int the latest commit 832d544fa643928f7fd5a5a556a4bbe5624bbce0
