### ISSUE TITLE
Multiple Errors with python 2.7.11 on OSX 10.10

### ISSUE THREAD

**Issue by BenjaminHCCarr** [aboul3la/Sublist3r#15]
`tyr:~/Code/github/Sublist3r (master) benc$ python2.7 sublist3r.py -d domainname.us -o ~/tmp/sublist3r.out | tee ~/tmp/sublist3r.tee.txt

                 ____        _     _ _     _   _____
                / ___| _   _| |__ | (_)___| |_|___ / _ __
                \___ \| | | | '_ \| | / __| __| |_ \| '__|
                 ___) | |_| | |_) | | \__ \ |_ ___) | |
                |____/ \__,_|_.__/|_|_|___/\__|____/|_|

    # Fast Subdomains Enumeration tool using Search Engines and BruteForce
    # Coded By Ahmed Aboul-Ela - @aboul3la
    # Special Thanks to Ibrahim Mosaad - @ibrahim_mosaad for his contributions
    
[-] Enumerating subdomains now for reticulum.us
[-] Searching now in Baidu..
[-] Searching now in Yahoo..
[-] Searching now in Google..
[-] Searching now in Bing..
[-] Searching now in Ask..
[-] Searching now in Netcraft..
[-] Searching now in DNSdumpster..
[!] Error: Google probably now is blocking our requests
[~] Finished now the Google Enumeration ...
Process NetcraftEnum-6:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "sublist3r.py", line 461, in run
    domain_list = self.enumerate()
  File "sublist3r.py", line 505, in enumerate
    resp = self.req(start_url)
  File "sublist3r.py", line 477, in req
    resp = self.session.get(url, headers=headers, timeout=self.timeout,cookies=cookies)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 459, in send
    raise ConnectTimeout(e, request=request)
ConnectTimeout: HTTPConnectionPool(host='searchdns.netcraft.com', port=80): Max retries exceeded with url: /?restriction=site+ends+with&host=example.com (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x10ca6e290>, 'Connection to searchdns.netcraft.com timed out. (connect timeout=10)'))
HTTPConnectionPool(host='searchdns.netcraft.com', port=80): Max retries exceeded with url: /?restriction=site+ends+with&host=example.com (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x10ca6e290>, 'Connection to searchdns.netcraft.com timed out. (connect timeout=10)'))`

No log file was written at all! Here is the output of the tee:
`tyr:~/Code/github/Sublist3r (master) benc$ cat ~/tmp/sublist3r.tee.txt 

                 ____        _     _ _     _   _____
                / ___| _   _| |__ | (_)___| |_|___ / _ __
                \___ \| | | | '_ \| | / __| __| |_ \| '__|
                 ___) | |_| | |_) | | \__ \ |_ ___) | |
                |____/ \__,_|_.__/|_|_|___/\__|____/|_|

    # Fast Subdomains Enumeration tool using Search Engines and BruteForce
    # Coded By Ahmed Aboul-Ela - @aboul3la
    # Special Thanks to Ibrahim Mosaad - @ibrahim_mosaad for his contributions
    
[-] Enumerating subdomains now for reticulum.us
[-] Searching now in Baidu..
[-] Searching now in Yahoo..
[-] Searching now in Google..
[-] Searching now in Bing..
[-] Searching now in Ask..
[-] Searching now in Netcraft..
[-] Searching now in DNSdumpster..
[!] Error: Google probably now is blocking our requests
[~] Finished now the Google Enumeration ...
HTTPConnectionPool(host='searchdns.netcraft.com', port=80): Max retries exceeded with url: /?restriction=site+ends+with&host=example.com (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x10ca6e290>, 'Connection to searchdns.netcraft.com timed out. (connect timeout=10)'))`

I  even tried:
`sudo pip2.7 freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U`

This did not change the errors

**Comment by aboul3la** [comment]
@BenjaminHCCarr looks like there was a problem with Netcraft website. I can't see this error now. 

So can you try again and let me know if it's fixed on your side too or it's still happening ?

**Comment by BenjaminHCCarr** [comment]
before new pull (same code as yesterday):
`[-] Searching now in DNSdumpster..
Process NetcraftEnum-6:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "sublist3r.py", line 461, in run
    domain_list = self.enumerate()
  File "sublist3r.py", line 506, in enumerate
    cookies = self.create_cookies(resp.headers['set-cookie'])
  File "/usr/local/lib/python2.7/site-packages/requests/structures.py", line 56, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'set-cookie'`

After tonight's pull:
`[-] Searching now in Baidu..
[-] Searching now in Yahoo..
[-] Searching now in Google..
[-] Searching now in Bing..
[-] Searching now in Ask..
[-] Searching now in Netcraft..
[-] Searching now in DNSdumpster..
[-] Total Unique Subdomains Found: 1`

No Netcraft error today, put it only pulled (1) subdomain a (CNAME) www.domain.
The domain has
`A: 2
AAAA: 4
CNAME: 11`

**Comment by aboul3la** [comment]
Looks like the enumeration is done correctly but it can't find any known subdomains in the search engines. you can try -b option to use bruteforce also maybe it will catch them.
