### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'content'

### ISSUE THREAD

**Issue by seanc** [aboul3la/Sublist3r#21]
https://asciinema.org/a/7r6ye52ojj3eqc13wygx6xcor

Python Version: 2.7.6

**Comment by aboul3la** [comment]
Thanks for reporting this issue, it should be fixed now in latest commit 85d2d1cab5dd9f3bc2b7e1bbac71bfb818fb4251

Kindly test it again and confirm if it was fixed.

Thanks
