### ISSUE TITLE
<BR> in output

### ISSUE THREAD

**Issue by gbiagomba** [aboul3la/Sublist3r#210]
Hello,

I noticed when I save output and I noticed the output included <BR> and this impacted my script when I tried using this output. Now I have since made changes to adjust for this so it does not impact me but I figured I let you know. 

```
                 ____        _     _ _     _   _____
                / ___| _   _| |__ | (_)___| |_|___ / _ __
                \___ \| | | | '_ \| | / __| __| |_ \| '__|
                 ___) | |_| | |_) | | \__ \ |_ ___) | |
                |____/ \__,_|_.__/|_|_|___/\__|____/|_|

                # Coded By Ahmed Aboul-Ela - @aboul3la
    
[-] Enumerating subdomains now for www.example.com
[-] verbosity is enabled, will show the subdomains results in realtime
[-] Searching now in Baidu..
[-] Searching now in Yahoo..
[-] Searching now in Google..
[-] Searching now in Bing..
[-] Searching now in Ask..
[-] Searching now in Netcraft..
[-] Searching now in DNSdumpster..
[-] Searching now in Virustotal..
[-] Searching now in ThreatCrowd..
[-] Searching now in SSL Certificates..
[-] Searching now in PassiveDNS..
Virustotal: preview.www.example.com
Virustotal: philly.www.example.com
SSL Certificates: preview.www.example.com<BR>www.example.com
SSL Certificates: preview.www.example.com
[-] Saving results to file: /tmp/tmp.YEwqVr1nVX/2020/01-09/Sublist3r/DR-2020Q1-www.example.com-sublist3r_output.txt
[-] Total Unique Subdomains Found: 3
preview.www.example.com<BR>www.example.com
philly.www.example.com
preview.www.example.com
``

**Comment by estebancano-dev** [comment]
same here!

**Comment by ttt123123** [comment]
same here

**Comment by RAVIPRAJ** [comment]
it is also repeating subdomain names in list
like
www.example.com<BR>wwwdev.example.com<BR>shop.example.com
wwwdev2.example.com<BR>shop.example.com

you can see there shop.example.com are comming 2 time
there 400 subdomains list showing 650 after some subdomain repeated in output

**Comment by aboul3la** [comment]
Hi,

Thanks for reporting this issue and apologies for the late response.

I just pushed a fix for the issue in commit 61ebf366e096ffdc9fea6bb57f00683af5944bfc.

Please update your version to the latest version using "git pull" command.

Thank you!

**Comment by estebancano-dev** [comment]
Thank you! Don't worry, it's free and you owe nobody!!

**Comment by gbiagomba** [comment]
@aboul3la no worries man, i will be sure to buy you a beer when i get to egypt!
