### ISSUE TITLE
solve : <BR> in output

### ISSUE THREAD

**Issue by c00ki33** [aboul3la/Sublist3r#221]
__1. Open `sublist3r.py` using any text editor__
__2. add this code at line 801__
```
if "<BR>" in subdomain:
                    subdomain = subdomain.replace("<BR>","\r\n")
```
__3. save__

![github](https://user-images.githubusercontent.com/55632595/75715407-a7b61300-5ccd-11ea-8a6e-585d97c60391.png)

**Comment by aboul3la** [comment]
Hi,

Thanks for reporting this issue.

I just pushed a fix for the issue in commit 61ebf366e096ffdc9fea6bb57f00683af5944bfc.
Please update your version to the latest version using "git pull" command.

Thank you!
