### ISSUE TITLE
<BR>

### ISSUE THREAD

**Issue by TROUBLE-1** [aboul3la/Sublist3r#224]
![Capture](https://user-images.githubusercontent.com/54508518/75957737-ac064a00-5ee0-11ea-9f9b-cd168ca9ac6e.JPG)

**Comment by m4ll0k** [comment]
#219

**Comment by aboul3la** [comment]
Hi,

I just pushed a fix for the issue in commit 61ebf366e096ffdc9fea6bb57f00683af5944bfc.
Please update your version to the latest version using "git pull" command.

Thank you!
