### ISSUE TITLE
Release Version not Equal 

### ISSUE THREAD

**Issue by xyu3xx** [aboul3la/Sublist3r#227]
The release .zip version (https://github.com/aboul3la/Sublist3r/archive/V1.0.zip) is not equal the file https://github.com/aboul3la/Sublist3r/blob/master/sublist3r.py

The release version has not the Fixed DNSdumpster engine by aboul3la

**Comment by aboul3la** [comment]
Hi, thanks for bringing this to my attention.

I will update the release version.

Thank you!

**Comment by aboul3la** [comment]
I just released the version 1.1 to match the latest commits.

https://github.com/aboul3la/Sublist3r/releases/tag/1.1

Thank you!
