### ISSUE TITLE
NetcraftEnum don't Work

### ISSUE THREAD

**Issue by xyu3xx** [aboul3la/Sublist3r#228]
The line 579 is:
`link_regx = re.compile('<a href="http://toolbar.netcraft.com/site_report\?url=(.*)">')`

The correct is:
`link_regx = re.compile('<a class="results-table__host" href="(.*?)" rel="nofollow">')`

**Comment by aboul3la** [comment]
Hi, 

Thanks for reporting this issue and apologies for this late response.

I will check this problem and will push a fix shortly.

Thank you!

**Comment by aboul3la** [comment]
It should be fixed now. I just pushed a fix for the issue in commit 6af1b8c22b5ca035818fbb04c54890896f9b181a.

@xyu3xx Kindly retest and let me know if you find any problems.

Thank you!
