### ISSUE TITLE
CrtSearch output with <BR>

### ISSUE THREAD

**Issue by xyu3xx** [aboul3la/Sublist3r#230]
When i run python sublist3r.py -d domain.com e ssl
The output comes with <BR>
Example:
`autodiscover.domain.com<BR>mail-ldn.domain.com<BR>mobileld.domain.com<BR>mobileldn.domain.com`
Because some ssl certificates have more than one domain, so crt.sh output comes with <BR>

Replace:
`self.subdomains.append(subdomain.strip())`

For:
`for sd in subdomain.strip().split("<BR>"):
    self.subdomains.append(sd)`

**Comment by aboul3la** [comment]
Hi,

Apologies for this late reply.

The issue has been resolved in commit 61ebf366e096ffdc9fea6bb57f00683af5944bfc.

Please update to the latest version using "git pull" command.

Thank you!
