### ISSUE TITLE
Showing Error While Running Without Network Connection

### ISSUE THREAD

**Issue by sh3r1n** [aboul3la/Sublist3r#235]
$ python3 ./sublist3r.py -d google.com

                 ____        _     _ _     _   _____                                    
                / ___| _   _| |__ | (_)___| |_|___ / _ __                               
                \___ \| | | | '_ \| | / __| __| |_ \| '__|                              
                 ___) | |_| | |_) | | \__ \ |_ ___) | |                                 
                |____/ \__,_|_.__/|_|_|___/\__|____/|_|                                 

                # Coded By Ahmed Aboul-Ela - @aboul3la                                  
                                                                                        
[-] Enumerating subdomains now for google.com
[-] Searching now in Baidu..
[-] Searching now in Yahoo..
[-] Searching now in Google..
[-] Searching now in Bing..
[-] Searching now in Ask..
[-] Searching now in Netcraft..
[-] Searching now in DNSdumpster..
[-] Searching now in Virustotal..
[-] Searching now in ThreatCrowd..
[-] Searching now in SSL Certificates..
[-] Searching now in PassiveDNS..
HTTPSConnectionPool(host='www.virustotal.com', port=443): Max retries exceeded with url: /ui/domains/google.com/subdomains (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fa57f9263d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
HTTPSConnectionPool(host='dnsdumpster.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fa57f926220>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
HTTPSConnectionPool(host='searchdns.netcraft.com', port=443): Max retries exceeded with url: /?restriction=site+ends+with&host=example.com (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fa57f8ab3a0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
Process GoogleEnum-4:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "./sublist3r.py", line 269, in run
    domain_list = self.enumerate()
  File "./sublist3r.py", line 240, in enumerate
    if not self.check_response_errors(resp):
  File "./sublist3r.py", line 304, in check_response_errors
    if (type(resp) is str or type(resp) is unicode) and 'Our systems have detected unusual traffic' in resp:
NameError: name 'unicode' is not defined
Process Virustotal-9:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "./sublist3r.py", line 269, in run
    domain_list = self.enumerate()
  File "./sublist3r.py", line 703, in enumerate
    resp = json.loads(resp)
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not int
Process DNSdumpster-8:
Process NetcraftEnum-7:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "./sublist3r.py", line 269, in run
    domain_list = self.enumerate()
  File "./sublist3r.py", line 570, in enumerate
    cookies = self.get_cookies(resp.headers)
AttributeError: 'NoneType' object has no attribute 'headers'
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "./sublist3r.py", line 269, in run
    domain_list = self.enumerate()
  File "./sublist3r.py", line 649, in enumerate
    token = self.get_csrftoken(resp)
  File "./sublist3r.py", line 644, in get_csrftoken
    token = csrf_regex.findall(resp)[0]
TypeError: expected string or bytes-like object

**Comment by amustaque97** [comment]
This issue is not related to the tool. This tool is not intended to work offline without an internet connection. @sh3r1n please close this issue.

**Comment by sh3r1n** [comment]
This error came while I was running the tool and the network  disconnected accidently
