### ISSUE TITLE
No module named 'dnslib'

### ISSUE THREAD

**Issue by ChrisLycan** [aboul3la/Sublist3r#238]
at first I was getting no module named 'dns' out of the subbrute folder provided, then I had noticed that the subbrute wasn't up to date with my separate install of subbrute so I imported over the files seeing as the dns module was in the separate install

now I come up with this
Traceback (most recent call last):
  File "sublist3r.py", line 21, in <module>
    from subbrute import subbrute
  File "/home/hermes/Sublist3r/subbrute/subbrute.py", line 10, in <module>
    import dnslib
ImportError: No module named 'dnslib'

Any ideas where to get the dnslib module? or is it incorrectly referring to the dnslib folder thinking it should be a module?

**Comment by ChrisLycan** [comment]
tried moving dnslib folder into Sublist3r folder, fixed that importation error, now I'm getting

Traceback (most recent call last):
  File "sublist3r.py", line 22, in <module>
    import dns.resolver
ImportError: No module named 'dns'

**Comment by ChrisLycan** [comment]
Fixed, hadn't ran setup.py

**Comment by hntrgo** [comment]
> Fixed, hadn't ran setup.py
> 

How do you fix it?

**Comment by ChrisLycan** [comment]
python setup.py (while cd into the Sublist3r dir in terminal)

**Comment by hntrgo** [comment]
![Screenshot_2020-05-21 Screenshot 2020-05-21 07 28 45 png (PNG Image, 1366 × 638 pixels) - Scaled (79%)](https://user-images.githubusercontent.com/65719493/82571380-bc20e380-9b37-11ea-9bce-a3807fbb614e.png)
tahat s what i get !!!

**Comment by ChrisLycan** [comment]
Try running one of the commands listed here dependent on which version of
python you have. It should give you the setuptools module that you're
missing before running setup.py

https://stackoverflow.com/questions/14426491/python-3-importerror-no-module-named-setuptools#14426553

**Comment by hntrgo** [comment]
Thanks  for response. I will try

**Comment by hntrgo** [comment]
Thanks for the reply i will try

**Comment by ChrisLycan** [comment]
No problem man, I hope you get it up n running, a big hint when you run
into errors is look at what the code spits back out at you before moving
forward. It traces back to the file and what line the issue is on, then
reports the error it's having. Which you then can search up to see if
anyone online has the solution for.
