### ISSUE TITLE
import request problem!

### ISSUE THREAD

**Issue by quaseD3V** [aboul3la/Sublist3r#325]
Hello lads, I'm getting this error then I run this command: 
 python sublist3r.py -b -d http://www.franc****om***ato.**.com

I'm take a look at 23 line in sublist3r.py , but I think all requirements is installed on my system!

Sublist3r$ python --version    =>         Python 2.7.18

how to solve this!
---------------------------------------------------------------------------------------
my error =>     Traceback (most recent call last):
                             File "sublist3r.py", line 23, in <module>
                               import requests
                          ImportError: No module named requests

-------------------------------------------------------------------------------------
my system run at 
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal

![Screenshot from 2022-01-01 10-04-03](https://user-images.githubusercontent.com/82067384/147851184-0c98b529-d5c2-4660-b57d-844cd2e7e424.png)

**Comment by hanzala123** [comment]
Can you try using Python3?

**Comment by AhmedSHelmi** [comment]
run `pip install requests` then try again.

**Comment by AhmedSHelmi** [comment]
did you do `sudo pip install -r requirements.txt` ?

**Comment by quaseD3V** [comment]
Hey lads thanks for try to help, I will use other tool, 

cheers!
