### ISSUE TITLE
How to scan localhost servers?

### ISSUE THREAD

**Issue by windowshopr** [aboul3la/Sublist3r#333]
Windows 10, Python 3.7.9. I have a few servers running on a local machine that I'd like to test on. Does this support IP addresses instead of url's? I've tried a few different combinations but to no avail.

The codes I've tried are below (local ip obfuscated with x's):

```
python sublist3r.py -d 172.x.x.82
python sublist3r.py -d http://172.x.x.82
python sublist3r.py -d http://172.x.x.82:5000
python sublist3r.py -d localhost
python sublist3r.py -d 127.0.0.1
```

All of which return:

`Error: Please enter a valid domain`

So wondering if it's possible. Thanks!

**Comment by lucthienphong1120** [comment]
i think because localhost doesn't have subdomain ? ie: www.localhost ? it is impossible
moreover, localhost can't be searched on google so the script can't work
