### ISSUE TITLE
Error on collecting requirements.txt when running on macbook

### ISSUE THREAD

**Issue by thefishermanhacker** [aboul3la/Sublist3r#34]
Hi!
I got the following errors while running: pip install requirements.txt.

`bash-3.2$ pip install requirements.txt
Collecting requirements.txt
  Could not find a version that satisfies the requirement requirements.txt (from versions: )
No matching distribution found for requirements.txt`

Thanks

**Comment by jamlamberti** [comment]
That is because pip is interpreting requirements.txt as a requirement specifier. The correct command to run is actually:

`$ pip install -r requirements.txt`

This tells pip to interpret each line in the requirements.txt file as a requirement specifier.

Let me know if this fixes it for you!

**Comment by thefishermanhacker** [comment]
Yea thats do the work.
Thanks

**Comment by jamlamberti** [comment]
@aboul3la This issue can be closed!

**Comment by aboul3la** [comment]
As @jamlamberti mentioned. The correct command should be ```pip install -r requirements.txt```. I will add that  also to README to make everyone aware of that.
