### ISSUE TITLE
not showing subdomain when using Sublist3r

### ISSUE THREAD

**Issue by mrlayy** [aboul3la/Sublist3r#355]
How to solve this problem? 

<img width="714" alt="Screenshot 2023-01-20 at 13 28 58" src="https://user-images.githubusercontent.com/93826691/213631814-07ee95df-3baf-4f46-8bd5-3b7060571783.png">

**Comment by HussainFathy** [comment]
same

**Comment by Eml0** [comment]
Same question for me.

**Comment by mrlayy** [comment]
I think sublist3r is no longer maintained and it is not a go to tool for subdomain enum

U can use another tools, https://github.com/projectdiscovery/subfinder

**Comment by mrlayy** [comment]
I think sublist3r is no longer maintained and it is not a go to tool for subdomain enum

U can use another tools, https://github.com/projectdiscovery/subfinder
