### ISSUE TITLE
Scan domains from newline delimited file

### ISSUE THREAD

**Issue by nwalsh1995** [aboul3la/Sublist3r#36]
It would be great to have the ability to scan multiple domains from one program.

Right now you can do a work around by looping through the file with domains and running a sublist3r process against each domain.

Subbrute also supports this with the '-t' option.

**Comment by aboul3la** [comment]
Thanks @nwalsh1995 for the suggestion, I'm currently working on adding this feature to Sublist3r and going to push it soon.

**Comment by the-st0rm** [comment]
I am really not sure if we want to do this or not. I still like sublister simple.. receiving one domain and returning all subdomains ... I don't want to keep adding more params. Especially when you can do that with a single loop on a bash shell something like

```
for domain in `cat domains.txt`;
do
sublist3r.py -d $domain;
done;
```

@aboul3la  what do you think?

**Comment by vincentcox** [comment]
Can't say it doesn't works but...
![image](https://user-images.githubusercontent.com/9286611/41855651-75d13ede-7893-11e8-8cbc-76254a459d80.png)
