### ISSUE TITLE
Readme should state which Python versions are supported

### ISSUE THREAD

**Issue by cclauss** [aboul3la/Sublist3r#4]
The `argparse `module is built into Python 3.2 and later.

**Comment by aboul3la** [comment]
Good point @cclauss , the Readme file was updated before to state how to install the argparse module in case it wasn't installed.i will update also the Readme with the supported python versions.

Thanks

**Comment by cclauss** [comment]
Closed via https://github.com/aboul3la/Sublist3r/commit/4cd8742a65b1fcaaaa45f52cad28ddce92d91b1e
