### ISSUE TITLE
handle ports & e-mail-adresses better

### ISSUE THREAD

**Issue by yoshimo** [aboul3la/Sublist3r#57]
If you get results like b.example.com:1234  and b.example.com , they should be unified in the summary.
Same goes for someuser@a.example.net. We care about the subdomain, not the localuser part of the e-mail adress

**Comment by aboul3la** [comment]
Can you show me a test case when did you see such output comes from Sublist3r ?

**Comment by yoshimo** [comment]
hamburg.de has E-Mail-Adresses in the SSL Certificates output.

**Comment by aboul3la** [comment]
Thanks @yoshimo for reporting this issue. This was weird behavior. 
i just pushed a fix for this issue and fixed the parsing function in the SSL Certs module.
