### ISSUE TITLE
two issues

### ISSUE THREAD

**Issue by zhangkaiyang** [aboul3la/Sublist3r#6]
1.the first one
Process AskEnum-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "sublist3r.py", line 196, in run
    domain_list = self.enumerate()
  File "sublist3r.py", line 164, in enumerate
    resp = self.send_req(query, page_no)
  File "sublist3r.py", line 110, in send_req
    return resp.text
AttributeError: 'Response' object has no attribute 'text'

if the "return resp.text" is false and should replace into "return resp" ?

2.a second one
Process BingEnum-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "sublist3r.py", line 196, in run
    domain_list = self.enumerate()
  File "sublist3r.py", line 169, in enumerate
    links = self.extract_domains(resp)
  File "sublist3r.py", line 369, in extract_domains
    return links_list
UnboundLocalError: local variable 'links_list' referenced before assignment

why dose the error occur?

**Comment by aboul3la** [comment]
@zhangkaiyang, does those two errors appears every time you run the tool or it happened once ?

**Comment by zhangkaiyang** [comment]
i know why it happend by using the google.my linux distributtion is ubuntu 12.04,and the version of module requests that i install by "sudo ape-get install python-requests"  is too low.so the first error occured.
In the first time, i don't know why,so i change the "resp.text" into "resp",then the second error happend.

**Comment by aboul3la** [comment]
Try to execute the following command: 

```sudo pip-2.7 install requests --upgrade```

or change **resp.text** to **resp.content** it should work.

Try it and let me know if it will be fixed.

i will push also a fix for this in the sublist3r.py .

**Comment by aboul3la** [comment]
Fixed in commit: a3aa220

@zhangkaiyang  update your version now using: git pull or or download the latest version tarball  https://github.com/aboul3la/Sublist3r/archive/master.zip
