### ISSUE TITLE
Add please this

### ISSUE THREAD

**Issue by shadowfolder** [aboul3la/Sublist3r#67]
Hi! Can you add please count to verbose? I need to see how much domains to brute left. In example

bruteforcing 0/10000
bruteforcing 100/10000
bruteforcing 3500/10000
bruteforcing 10000/10000 (complete)

**Comment by aboul3la** [comment]
Hi @shadowfolder, Thanks for your suggestion. The bruteforce in Sublist3r depends on subbrute tool (I'm not the author of it) and it will need modifications in the core in subbrute to do it. I might try to do it in the future but I can't promise now.
