### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by Plazmaz** [aboul3la/Sublist3r#69]
It's been a while since the last commit and my PR hasn't had any activity. Are you still maintaining this project?

**Comment by the-st0rm** [comment]
It is alive, but kind of moving slow. We only have 4 pull requests and not a lot of issues? I am not sure if I am missing something?!

**Comment by Plazmaz** [comment]
Good to hear it! I was simply wondering as some of the more recent issue sand PRs haven't been responded to.

**Comment by jamesbercegay** [comment]
I think the answer now seems to be "no"?
