### ISSUE TITLE
false positive subdomains

### ISSUE THREAD

**Issue by mikkz** [aboul3la/Sublist3r#95]
Got lots of false positive subdomains on the output, still tryna find a way to update the resolver but i dont have any clue with it haha

**Comment by aboul3la** [comment]
I will fix this issue in the upcoming version. I will validate all the returned subdomains as few sources that gives historical dns records might return some DNS records which doesn't resolve to an IP Address.

**Comment by mikkz** [comment]
Great! Thanks for the awesome tool @aboul3la  !
